import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { useState, useMemo } from 'react'


interface Pokemon {
  id: number
  name: string
  image: string
}


export async function getServerSideProps() {
  const resp = await fetch("https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json")
  return {
    props: {
      pokemon: await resp.json()
    }
  }
}


export default function Home({ pokemon }: { pokemon: Pokemon[] }) {
  const [filter, setFilter] = useState("")
  const filteredPokemon = useMemo(() => pokemon.filter(p => p.name.toLowerCase().includes(filter.toLowerCase())), [filter, pokemon])

  return (
    <main className={styles.main}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <input type="text" className={styles.filter} value={filter} onChange={(e) => setFilter(e.target.value)} />
      </div>
      <div className={styles.container}>
        {filteredPokemon.slice(0, 20).map(pokemon => (
          <div key={pokemon.id} className={styles.image}>
            <Image src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${pokemon.image}`} alt={pokemon.name} width={200} height={200} />
            <h2>{pokemon.name}</h2>
          </div>
        ))}
      </div>
    </main>
  )
}
